export const VOID_ELEMENTS = new Set([
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
]);

export const RAW_TEXT_ELEMENTS = new Set([
  "script",
  "style",
  "textarea",
  "title",
]);

export const AUTO_CLOSE_RULES: Record<string, string[]> = {
  li: ["li"],
  dt: ["dt", "dd"],
  dd: ["dt", "dd"],
  address: ["p"],
  article: ["p"],
  aside: ["p"],
  blockquote: ["p"],
  center: ["p"],
  details: ["p"],
  dialog: ["p"],
  dir: ["p"],
  div: ["p"],
  dl: ["p"],
  fieldset: ["p"],
  figcaption: ["p"],
  figure: ["p"],
  footer: ["p"],
  form: ["p"],
  h1: ["p"],
  h2: ["p"],
  h3: ["p"],
  h4: ["p"],
  h5: ["p"],
  h6: ["p"],
  header: ["p"],
  hgroup: ["p"],
  hr: ["p"],
  listing: ["p"],
  main: ["p"],
  menu: ["p"],
  nav: ["p"],
  ol: ["p"],
  p: ["p"],
  pre: ["p"],
  section: ["p"],
  summary: ["p"],
  table: ["p"],
  ul: ["p"],
  rt: ["rt", "rp"],
  rp: ["rt", "rp"],
  optgroup: ["optgroup"],
  option: ["option"],
  thead: ["tbody", "tfoot"],
  tbody: ["thead", "tbody", "tfoot"],
  tfoot: ["thead", "tbody"],
  tr: ["tr"],
  td: ["td", "th"],
  th: ["td", "th"],
};

export const FORMATTING_ELEMENTS = new Set([
  "a",
  "b",
  "big",
  "code",
  "em",
  "font",
  "i",
  "nobr",
  "s",
  "small",
  "strike",
  "strong",
  "tt",
  "u",
]);

export const TABLE_SCOPE_ELEMENTS = new Set([
  "table",
  "tbody",
  "thead",
  "tfoot",
  "tr",
  "template",
  "html",
]);

export const TABLE_CONTEXT_ELEMENTS = new Set([
  "table",
  "tbody",
  "thead",
  "tfoot",
  "tr",
]);

export const VALID_TABLE_CHILDREN = new Set([
  "caption",
  "colgroup",
  "col",
  "tbody",
  "thead",
  "tfoot",
  "tr",
  "script",
  "template",
  "style",
]);

export const VALID_TABLE_SECTION_CHILDREN = new Set([
  "tr",
  "script",
  "template",
  "style",
]);

export const VALID_TR_CHILDREN = new Set([
  "td",
  "th",
  "script",
  "template",
  "style",
]);
